target 'ReactNativeStarter' do
  # Native Navigation uses Swift, so this line is required!
  use_frameworks!

  # Native Navigation!
  pod 'native-navigation', :path => '../node_modules/native-navigation'

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'Yoga', :path => '../../react-native/ReactCommon/yoga'

  # Third party deps
  pod 'DoubleConversion', :podspec => '../../react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../../react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../../react-native/third-party-podspecs/Folly.podspec'

  # You don't necessarily need all of these subspecs, but this would be a typical setup.
  pod 'React', :path => '../../react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTNetwork',
    # Add any other subspecs you want to use in your project
    'DevSupport'
  ]

  # Add any other dependencies here, including any 3rd party native libraries that you depend on for
  # React Native.
end
